### ISSUE TITLE
Use CEL to encode oneof rules

### ISSUE THREAD

**Issue by mkmik** [yandex/protoc-gen-crd#1]
`oneof` groups with protobuf semantics cannot be encoded as jsonschema but kubernetes CRD can include custom CEL expressions that can encode the protobuf semantics:

```proto
message M {
    oneof group1 {
        string s1 = 1;
        string s2 = 2;
        string s3 = 3;
    }
    oneof group2 {
        string s4 = 4;
        string s5 = 5;
        string s6 = 6;
    }
}
```

```yaml
properties:
  s1: {type: string}
  s2: {type: string}
  s3: {type: string}
  s4: {type: string}
  s5: {type: string}
  s6: {type: string}
type: object

x-kubernetes-validations:
- rule: "(has(self.s1)?1:0) + (has(self.s2)?1:0) + (has(self.s3)?1:0) <= 1"
  message: "oneof group1 must be exclusive"
- rule: "(has(self.s4)?1:0) + (has(self.s5)?1:0) + (has(self.s6)?1:0) <= 1"
  message: "oneof group2 must be exclusive"
```

the number and size of the CEL expressions grows linearly with the fields in message M

----

equivalent CEL expression which may or may be not be more readable:

```yaml
x-kubernetes-validations:
- rule: "[has(self.s1), has(self.s2), has(self.s3)].filter(x, x).size() <= 1"
  message: "oneof group1 must be exclusive"
- rule: "[has(self.s4), has(self.s5), has(self.s6)].filter(x, x).size() <= 1"
  message: "oneof group2 must be exclusive"
```
